package ical

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
	"time"

	ics "github.com/arran4/golang-ical"
	"github.com/teambition/rrule-go"
)

// maxOccurrencesPerSeries bounds expansion of a single recurring series so that
// an unbounded RRULE cannot exhaust memory.
const maxOccurrencesPerSeries = 2000

// defaultWindowPast and defaultWindowFuture bound recurrence expansion when the
// caller supplies no date range. Without bounds an unbounded RRULE has no
// natural stopping point.
const (
	defaultWindowPast   = -1 * 365 * 24 * time.Hour
	defaultWindowFuture = 2 * 365 * 24 * time.Hour
)

// httpTimeout caps the fetch of a remote calendar.
const httpTimeout = 30 * time.Second

type RemoteCalendar struct {
	URL         string `json:"url" yaml:"url"`
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description" yaml:"description"`
}

type Event struct {
	UID         string    `json:"uid"`
	Summary     string    `json:"summary"`
	Description string    `json:"description"`
	Location    string    `json:"location"`
	Start       time.Time `json:"start"`
	End         time.Time `json:"end"`
	Status      string    `json:"status"`
	Organizer   string    `json:"organizer,omitempty"`
	Attendees   []string  `json:"attendees,omitempty"`
	Categories  []string  `json:"categories,omitempty"`
	RecurRule   string    `json:"recurrence_rule,omitempty"`
	AllDay      bool      `json:"all_day"`
	// Recurring is true when this event was generated by expanding an RRULE
	// rather than read directly from a VEVENT.
	Recurring bool `json:"recurring,omitempty"`
}

// eventTemplate holds the timezone-resolved fields of a single VEVENT before
// recurrence expansion.
type eventTemplate struct {
	base         Event
	start        time.Time
	duration     time.Duration
	rrule        string
	exdates      map[time.Time]bool
	rdates       []time.Time
	recurrenceID time.Time
	hasRecurID   bool
}

func Fetch(url string) ([]byte, error) {
	client := &http.Client{Timeout: httpTimeout}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("calendar fetch returned HTTP %d %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(bytes.TrimSpace(data)) == 0 {
		return nil, fmt.Errorf("calendar fetch returned an empty body")
	}
	if !bytes.Contains(data, []byte("BEGIN:VCALENDAR")) {
		return nil, fmt.Errorf("response is not an iCalendar document (content-type %q)", resp.Header.Get("Content-Type"))
	}
	return data, nil
}

func FetchAndParse(url string, startDate, endDate *time.Time) ([]Event, error) {
	data, err := Fetch(url)
	if err != nil {
		return nil, err
	}
	return Parse(data, startDate, endDate)
}

// Parse reads an iCalendar document, expands recurring series, and returns the
// occurrences overlapping the supplied window. Both bounds are optional.
func Parse(data []byte, startDate, endDate *time.Time) ([]Event, error) {
	cal, err := ics.ParseCalendar(bytes.NewReader(data))
	if err != nil {
		return nil, err
	}

	tz := newTZResolver(cal)

	// Expansion needs a bounded window even when the caller supplies none.
	now := time.Now()
	windowStart := now.Add(defaultWindowPast)
	windowEnd := now.Add(defaultWindowFuture)
	if startDate != nil {
		windowStart = *startDate
	}
	if endDate != nil {
		windowEnd = *endDate
	}
	if windowEnd.Before(windowStart) {
		return nil, fmt.Errorf("end_date %s is before start_date %s",
			windowEnd.Format(time.RFC3339), windowStart.Format(time.RFC3339))
	}

	var masters []*eventTemplate
	// overrides maps UID -> recurrence instant -> the modified instance.
	overrides := make(map[string]map[time.Time]*eventTemplate)

	for _, ev := range cal.Events() {
		tpl, err := buildTemplate(ev, tz)
		if err != nil {
			// A single malformed VEVENT should not discard the whole calendar.
			continue
		}
		if tpl.hasRecurID {
			uid := tpl.base.UID
			if overrides[uid] == nil {
				overrides[uid] = make(map[time.Time]*eventTemplate)
			}
			overrides[uid][tpl.recurrenceID.UTC()] = tpl
			continue
		}
		masters = append(masters, tpl)
	}

	events := []Event{}
	seenOverrides := make(map[string]map[time.Time]bool)

	for _, tpl := range masters {
		occurrences := expand(tpl, windowStart, windowEnd)
		for _, occ := range occurrences {
			inst := occ.UTC()

			// A RECURRENCE-ID instance replaces the generated occurrence.
			if byUID, ok := overrides[tpl.base.UID]; ok {
				if ov, ok := byUID[inst]; ok {
					if seenOverrides[tpl.base.UID] == nil {
						seenOverrides[tpl.base.UID] = make(map[time.Time]bool)
					}
					seenOverrides[tpl.base.UID][inst] = true
					if e, ok := materialize(ov, ov.start, true); ok && overlaps(e, windowStart, windowEnd) {
						events = append(events, e)
					}
					continue
				}
			}

			e, ok := materialize(tpl, occ, tpl.rrule != "")
			if !ok || !overlaps(e, windowStart, windowEnd) {
				continue
			}
			events = append(events, e)
		}
	}

	// Overrides whose master series is absent, or whose instant was moved
	// outside the expansion window, still represent real events.
	for uid, byInstant := range overrides {
		for inst, ov := range byInstant {
			if seenOverrides[uid][inst] {
				continue
			}
			if e, ok := materialize(ov, ov.start, true); ok && overlaps(e, windowStart, windowEnd) {
				events = append(events, e)
			}
		}
	}

	sort.Slice(events, func(i, j int) bool {
		if events[i].Start.Equal(events[j].Start) {
			return events[i].Summary < events[j].Summary
		}
		return events[i].Start.Before(events[j].Start)
	})

	return events, nil
}

// buildTemplate reads one VEVENT into a timezone-resolved template.
func buildTemplate(event *ics.VEvent, tz *tzResolver) (*eventTemplate, error) {
	tpl := &eventTemplate{
		base:    Event{UID: event.Id()},
		exdates: make(map[time.Time]bool),
	}

	if prop := event.GetProperty(ics.ComponentPropertySummary); prop != nil {
		tpl.base.Summary = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyLocation); prop != nil {
		tpl.base.Location = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyStatus); prop != nil {
		tpl.base.Status = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyDescription); prop != nil {
		tpl.base.Description = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyOrganizer); prop != nil {
		tpl.base.Organizer = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyRrule); prop != nil {
		tpl.rrule = prop.Value
		tpl.base.RecurRule = prop.Value
	}

	for _, prop := range event.Properties {
		switch prop.IANAToken {
		case string(ics.ComponentPropertyAttendee):
			tpl.base.Attendees = append(tpl.base.Attendees, prop.Value)
		case string(ics.ComponentPropertyCategories):
			// CATEGORIES is a comma-separated list within a single property.
			for _, c := range strings.Split(prop.Value, ",") {
				if c = strings.TrimSpace(c); c != "" {
					tpl.base.Categories = append(tpl.base.Categories, c)
				}
			}
		}
	}

	// DTSTART is mandatory; without it the event cannot be placed in time.
	dtstart := event.GetProperty(ics.ComponentPropertyDtStart)
	if dtstart == nil {
		return nil, fmt.Errorf("event %q has no DTSTART", tpl.base.UID)
	}
	start, allDay, err := parseDateTime(dtstart.Value, paramTZID(dtstart), tz)
	if err != nil {
		return nil, err
	}
	tpl.start = start
	tpl.base.AllDay = allDay

	// Duration comes from DTEND, or DURATION, or defaults by event kind.
	tpl.duration = eventDuration(event, start, allDay, tz)

	if p := event.GetProperty(ics.ComponentProperty(ics.PropertyRecurrenceId)); p != nil {
		if rid, _, err := parseDateTime(p.Value, paramTZID(p), tz); err == nil {
			tpl.recurrenceID = rid
			tpl.hasRecurID = true
		}
	}

	// EXDATE and RDATE may each appear multiple times, and each may carry a
	// comma-separated list of values.
	for _, prop := range event.Properties {
		switch prop.IANAToken {
		case string(ics.PropertyExdate):
			for _, v := range strings.Split(prop.Value, ",") {
				if t, _, err := parseDateTime(strings.TrimSpace(v), paramTZID(&prop), tz); err == nil {
					tpl.exdates[t.UTC()] = true
				}
			}
		case string(ics.PropertyRdate):
			for _, v := range strings.Split(prop.Value, ",") {
				// RDATE values may be periods ("start/end"); take the start.
				v = strings.TrimSpace(v)
				if i := strings.Index(v, "/"); i > 0 {
					v = v[:i]
				}
				if t, _, err := parseDateTime(v, paramTZID(&prop), tz); err == nil {
					tpl.rdates = append(tpl.rdates, t)
				}
			}
		}
	}

	return tpl, nil
}

func paramTZID(prop *ics.IANAProperty) string {
	if prop == nil {
		return ""
	}
	if vals, ok := prop.ICalParameters[string(ics.PropertyTzid)]; ok && len(vals) > 0 {
		return vals[0]
	}
	return ""
}

// parseDateTime interprets an iCalendar date or date-time value. It reports
// whether the value was a date-only (all-day) form.
func parseDateTime(value, tzid string, tz *tzResolver) (time.Time, bool, error) {
	value = strings.TrimSpace(value)

	// Date-only form: YYYYMMDD (all-day).
	if len(value) == 8 {
		t, err := time.ParseInLocation("20060102", value, time.UTC)
		if err != nil {
			return time.Time{}, false, err
		}
		if loc := tz.load(tzid, t); loc != nil {
			t, _ = time.ParseInLocation("20060102", value, loc)
		}
		return t, true, nil
	}

	// UTC form: YYYYMMDDTHHMMSSZ.
	if strings.HasSuffix(value, "Z") {
		t, err := time.ParseInLocation("20060102T150405Z", value, time.UTC)
		if err != nil {
			return time.Time{}, false, err
		}
		return t, false, nil
	}

	// Local form: YYYYMMDDTHHMMSS, interpreted in TZID if present.
	naive, err := time.ParseInLocation("20060102T150405", value, time.UTC)
	if err != nil {
		return time.Time{}, false, err
	}
	loc := tz.load(tzid, naive)
	if loc == nil {
		// Floating time, or an unresolvable zone: fall back to local time so the
		// event still lands on the correct calendar day.
		loc = time.Local
	}
	t, err := time.ParseInLocation("20060102T150405", value, loc)
	if err != nil {
		return time.Time{}, false, err
	}
	return t, false, nil
}

// eventDuration derives the length of an event from DTEND or DURATION.
func eventDuration(event *ics.VEvent, start time.Time, allDay bool, tz *tzResolver) time.Duration {
	if dtend := event.GetProperty(ics.ComponentProperty(ics.PropertyDtend)); dtend != nil {
		if end, _, err := parseDateTime(dtend.Value, paramTZID(dtend), tz); err == nil {
			if d := end.Sub(start); d >= 0 {
				return d
			}
		}
	}
	if dur := event.GetProperty(ics.ComponentProperty(ics.PropertyDuration)); dur != nil {
		if d, err := parseICalDuration(dur.Value); err == nil && d >= 0 {
			return d
		}
	}
	if allDay {
		return 24 * time.Hour
	}
	// RFC 5545: a date-time DTSTART with no DTEND or DURATION is instantaneous.
	return 0
}

// parseICalDuration parses an RFC 5545 duration such as "PT1H30M" or "P2DT3H".
func parseICalDuration(s string) (time.Duration, error) {
	s = strings.TrimSpace(s)
	neg := false
	if strings.HasPrefix(s, "-") {
		neg = true
		s = s[1:]
	} else if strings.HasPrefix(s, "+") {
		s = s[1:]
	}
	if !strings.HasPrefix(s, "P") {
		return 0, fmt.Errorf("invalid duration %q", s)
	}
	s = s[1:]

	var total time.Duration
	var num int
	inTime := false
	seenDigit := false

	for _, r := range s {
		switch {
		case r >= '0' && r <= '9':
			num = num*10 + int(r-'0')
			seenDigit = true
		case r == 'T':
			inTime = true
			num, seenDigit = 0, false
		case r == 'W' && seenDigit:
			total += time.Duration(num) * 7 * 24 * time.Hour
			num, seenDigit = 0, false
		case r == 'D' && seenDigit:
			total += time.Duration(num) * 24 * time.Hour
			num, seenDigit = 0, false
		case r == 'H' && inTime && seenDigit:
			total += time.Duration(num) * time.Hour
			num, seenDigit = 0, false
		case r == 'M' && inTime && seenDigit:
			total += time.Duration(num) * time.Minute
			num, seenDigit = 0, false
		case r == 'S' && inTime && seenDigit:
			total += time.Duration(num) * time.Second
			num, seenDigit = 0, false
		default:
			return 0, fmt.Errorf("invalid duration %q", s)
		}
	}
	if neg {
		total = -total
	}
	return total, nil
}

// expand returns the start instants of a template within the window, honouring
// RRULE, RDATE and EXDATE.
func expand(tpl *eventTemplate, windowStart, windowEnd time.Time) []time.Time {
	if tpl.rrule == "" && len(tpl.rdates) == 0 {
		if tpl.exdates[tpl.start.UTC()] {
			return nil
		}
		return []time.Time{tpl.start}
	}

	var out []time.Time
	if tpl.rrule != "" {
		opt, err := rrule.StrToROption(tpl.rrule)
		if err != nil {
			// An unparseable rule still has a real first occurrence.
			return []time.Time{tpl.start}
		}
		opt.Dtstart = tpl.start
		rr, err := rrule.NewRRule(*opt)
		if err != nil {
			return []time.Time{tpl.start}
		}
		// Widen the query by the event duration so a series occurrence that
		// starts before the window but runs into it is still produced.
		queryStart := windowStart.Add(-tpl.duration)
		for _, t := range rr.Between(queryStart, windowEnd, true) {
			out = append(out, t)
			if len(out) >= maxOccurrencesPerSeries {
				break
			}
		}
	}
	out = append(out, tpl.rdates...)

	filtered := out[:0]
	seen := make(map[time.Time]bool, len(out))
	for _, t := range out {
		key := t.UTC()
		if tpl.exdates[key] || seen[key] {
			continue
		}
		seen[key] = true
		filtered = append(filtered, t)
	}
	return filtered
}

// materialize produces a concrete Event for one occurrence instant.
func materialize(tpl *eventTemplate, start time.Time, recurring bool) (Event, bool) {
	if start.IsZero() {
		return Event{}, false
	}
	e := tpl.base
	e.Start = start
	e.End = start.Add(tpl.duration)
	e.Recurring = recurring
	// Copy slices so expanded occurrences do not alias one another.
	if len(tpl.base.Attendees) > 0 {
		e.Attendees = append([]string(nil), tpl.base.Attendees...)
	}
	if len(tpl.base.Categories) > 0 {
		e.Categories = append([]string(nil), tpl.base.Categories...)
	}
	return e, true
}

// overlaps reports whether an event intersects the window. An event that starts
// before the window but is still running inside it counts as overlapping;
// zero-length events count when they fall on the window's start boundary.
func overlaps(e Event, windowStart, windowEnd time.Time) bool {
	if !e.Start.Before(windowEnd) {
		return false
	}
	if e.End.Equal(e.Start) {
		return !e.Start.Before(windowStart)
	}
	return e.End.After(windowStart)
}
