package ical

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net"
	"net/http"
	"sort"
	"strings"
	"syscall"
	"time"

	ics "github.com/arran4/golang-ical"
	log "github.com/sirupsen/logrus"
	"github.com/teambition/rrule-go"
)

// maxOccurrencesPerSeries bounds expansion of a single recurring series so that
// an unbounded RRULE cannot exhaust memory.
const maxOccurrencesPerSeries = 2000

// defaultWindowPast and defaultWindowFuture bound recurrence expansion when the
// caller supplies no date range. Without bounds an unbounded RRULE has no
// natural stopping point.
const (
	defaultWindowPast   = -1 * 365 * 24 * time.Hour
	defaultWindowFuture = 2 * 365 * 24 * time.Hour
)

// httpTimeout caps the fetch of a remote calendar.
const httpTimeout = 30 * time.Second

// maxCalendarBytes caps how much of a response is read. A published calendar is
// a few megabytes at most; without a bound, one oversized or hostile feed can
// exhaust memory for the whole server.
const maxCalendarBytes = 64 << 20

// FetchOptions controls how a calendar is retrieved.
type FetchOptions struct {
	// AllowPrivateHosts permits connecting to loopback, link-local and private
	// addresses. Configured calendars may legitimately be self-hosted, so they
	// set this; a URL that arrived in a tool call must not, or the server
	// becomes a way to probe the network it runs in and read the results back.
	AllowPrivateHosts bool
}

// errPrivateAddress reports a refusal to connect to a non-public address.
type errPrivateAddress struct{ addr string }

func (e errPrivateAddress) Error() string {
	return fmt.Sprintf("refusing to fetch from non-public address %s: "+
		"only configured calendars may point at private hosts", e.addr)
}

// newHTTPClient builds a client that optionally refuses non-public addresses.
//
// The check runs in the dialer's Control hook rather than on the URL, so it sees
// the address actually being connected to. Checking the hostname up front would
// miss a redirect to an internal host, and would be defeated by a name that
// resolves publicly once and privately on the second lookup.
func newHTTPClient(opts FetchOptions) *http.Client {
	dialer := &net.Dialer{Timeout: 10 * time.Second, KeepAlive: 30 * time.Second}
	if !opts.AllowPrivateHosts {
		dialer.Control = func(network, address string, _ syscall.RawConn) error {
			host, _, err := net.SplitHostPort(address)
			if err != nil {
				return err
			}
			ip := net.ParseIP(host)
			if ip == nil || !isPublicIP(ip) {
				return errPrivateAddress{addr: host}
			}
			return nil
		}
	}

	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.DialContext = dialer.DialContext
	return &http.Client{Timeout: httpTimeout, Transport: transport}
}

// isPublicIP reports whether an address is routable on the public internet.
func isPublicIP(ip net.IP) bool {
	if ip.IsLoopback() || ip.IsPrivate() || ip.IsUnspecified() ||
		ip.IsLinkLocalUnicast() || ip.IsLinkLocalMulticast() ||
		ip.IsInterfaceLocalMulticast() || ip.IsMulticast() {
		return false
	}
	// Carrier-grade NAT, 100.64.0.0/10. Not private by Go's definition, but not
	// somewhere a published calendar is served from either.
	if v4 := ip.To4(); v4 != nil && v4[0] == 100 && v4[1] >= 64 && v4[1] <= 127 {
		return false
	}
	return true
}

type RemoteCalendar struct {
	URL         string `json:"url" yaml:"url"`
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description" yaml:"description"`
}

type Event struct {
	UID         string    `json:"uid"`
	Summary     string    `json:"summary"`
	Description string    `json:"description"`
	Location    string    `json:"location"`
	Start       time.Time `json:"start"`
	End         time.Time `json:"end"`
	Status      string    `json:"status"`
	Organizer   string    `json:"organizer,omitempty"`
	Attendees   []string  `json:"attendees,omitempty"`
	Categories  []string  `json:"categories,omitempty"`
	RecurRule   string    `json:"recurrence_rule,omitempty"`
	AllDay      bool      `json:"all_day"`
	// Recurring is true when this event was generated by expanding an RRULE
	// rather than read directly from a VEVENT.
	Recurring bool `json:"recurring,omitempty"`
}

// eventTemplate holds the timezone-resolved fields of a single VEVENT before
// recurrence expansion.
type eventTemplate struct {
	base     Event
	start    time.Time
	duration time.Duration
	rrule    string
	exdates  map[time.Time]bool
	rdates   []time.Time
	// tzid, startWall and wallBased carry DTSTART as it was written when it
	// named a zone, so a series can be repeated on the wall clock and each
	// occurrence placed at the offset in force on its own date.
	tzid         string
	startWall    time.Time
	wallBased    bool
	recurrenceID time.Time
	hasRecurID   bool
	// thisAndFuture is RANGE=THISANDFUTURE: the edit reaches every later
	// occurrence too, not only the slot it names.
	thisAndFuture bool
}

// overrideSet holds the edited instances of one series, split by how far each
// edit reaches.
//
// RECURRENCE-ID names the slot an instance replaces. With RANGE=THISANDFUTURE
// it replaces that slot and every later one — what a client writes when you
// choose "this and all following events" — so the two kinds cannot be looked up
// the same way: one matches an instant exactly, the other governs a range.
type overrideSet struct {
	single map[time.Time]*eventTemplate
	future []*eventTemplate // ascending by recurrenceID
}

func newOverrideSet() *overrideSet {
	return &overrideSet{single: make(map[time.Time]*eventTemplate)}
}

func (s *overrideSet) add(tpl *eventTemplate) {
	if tpl.thisAndFuture {
		s.future = append(s.future, tpl)
		return
	}
	s.single[tpl.recurrenceID.UTC()] = tpl
}

func (s *overrideSet) sortFuture() {
	sort.Slice(s.future, func(i, j int) bool {
		return s.future[i].recurrenceID.Before(s.future[j].recurrenceID)
	})
}

// governing returns the THISANDFUTURE edit in force at an occurrence: the last
// one that begins at or before it, so a later edit supersedes an earlier one.
func (s *overrideSet) governing(at time.Time) (*eventTemplate, bool) {
	var found *eventTemplate
	for _, ov := range s.future {
		if ov.recurrenceID.After(at) {
			break
		}
		found = ov
	}
	return found, found != nil
}

// shift is how far this edit moved its own slot, and therefore how far it moves
// every slot it governs: "move the whole series an hour later from here on".
func (t *eventTemplate) shift() time.Duration {
	return t.start.Sub(t.recurrenceID)
}

func Fetch(ctx context.Context, url string, opts FetchOptions) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}

	resp, err := newHTTPClient(opts).Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("calendar fetch returned HTTP %d %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, maxCalendarBytes+1))
	if err != nil {
		return nil, err
	}
	if len(data) > maxCalendarBytes {
		return nil, fmt.Errorf("calendar is larger than the %d MiB limit", maxCalendarBytes>>20)
	}
	if len(bytes.TrimSpace(data)) == 0 {
		return nil, fmt.Errorf("calendar fetch returned an empty body")
	}
	if !bytes.Contains(data, []byte("BEGIN:VCALENDAR")) {
		return nil, fmt.Errorf("response is not an iCalendar document (content-type %q)", resp.Header.Get("Content-Type"))
	}
	return data, nil
}

func FetchAndParse(ctx context.Context, url string, opts FetchOptions, startDate, endDate *time.Time) ([]Event, error) {
	data, err := Fetch(ctx, url, opts)
	if err != nil {
		return nil, err
	}
	return Parse(data, startDate, endDate)
}

// Parse reads an iCalendar document, expands recurring series, and returns the
// occurrences overlapping the supplied window. Both bounds are optional.
func Parse(data []byte, startDate, endDate *time.Time) ([]Event, error) {
	cal, err := ics.ParseCalendar(bytes.NewReader(data))
	if err != nil {
		return nil, err
	}

	tz := newTZResolver(cal)

	// Expansion needs a bounded window even when the caller supplies none.
	now := time.Now()
	windowStart := now.Add(defaultWindowPast)
	windowEnd := now.Add(defaultWindowFuture)
	if startDate != nil {
		windowStart = *startDate
	}
	if endDate != nil {
		windowEnd = *endDate
	}
	if windowEnd.Before(windowStart) {
		return nil, fmt.Errorf("end_date %s is before start_date %s",
			windowEnd.Format(time.RFC3339), windowStart.Format(time.RFC3339))
	}

	var masters []*eventTemplate
	overrides := make(map[string]*overrideSet)
	hasMaster := make(map[string]bool)

	for _, ev := range cal.Events() {
		tpl, err := buildTemplate(ev, tz)
		if err != nil {
			// A single malformed VEVENT should not discard the whole calendar.
			continue
		}
		if tpl.hasRecurID {
			uid := tpl.base.UID
			if overrides[uid] == nil {
				overrides[uid] = newOverrideSet()
			}
			overrides[uid].add(tpl)
			continue
		}
		masters = append(masters, tpl)
		hasMaster[tpl.base.UID] = true
	}
	for _, set := range overrides {
		set.sortFuture()
	}

	events := []Event{}
	seenOverrides := make(map[string]map[time.Time]bool)

	for _, tpl := range masters {
		set := overrides[tpl.base.UID]
		occurrences := expand(tpl, tz, windowStart, windowEnd)
		for _, occ := range occurrences {
			inst := occ.UTC()

			source, start := tpl, occ
			if set != nil {
				gov, governed := set.governing(occ)

				// The slot a single override names. Normally that is the
				// instant the rule generated, but once a THISANDFUTURE edit has
				// moved the series, clients differ over whether a later
				// RECURRENCE-ID names the original slot or the moved one. Both
				// identify the same occurrence, so both are accepted.
				key := inst
				ov, ok := set.single[key]
				if !ok && governed {
					key = occ.Add(gov.shift()).UTC()
					ov, ok = set.single[key]
				}

				switch {
				case ok:
					// A single-instance override replaces exactly this slot,
					// and is emitted at its own DTSTART. It beats a range edit:
					// naming one occurrence is the more specific statement.
					if seenOverrides[tpl.base.UID] == nil {
						seenOverrides[tpl.base.UID] = make(map[time.Time]bool)
					}
					seenOverrides[tpl.base.UID][key] = true
					source, start = ov, ov.start
				case governed:
					// RANGE=THISANDFUTURE: the edit owns this occurrence and
					// every later one, moved by however far it moved its own.
					source, start = gov, occ.Add(gov.shift())
				}
			}

			e, ok := materialize(source, start, tpl.rrule != "" || len(tpl.rdates) > 0)
			if !ok || !overlaps(e, windowStart, windowEnd) {
				continue
			}
			events = append(events, e)
		}
	}

	// Overrides whose master series is absent, or whose instant was moved
	// outside the expansion window, still represent real events.
	for uid, set := range overrides {
		for inst, ov := range set.single {
			if seenOverrides[uid][inst] {
				continue
			}
			if e, ok := materialize(ov, ov.start, true); ok && overlaps(e, windowStart, windowEnd) {
				events = append(events, e)
			}
		}
		// A THISANDFUTURE override is normally materialized through the
		// occurrences it governs. With no series to govern, it is just an event.
		if hasMaster[uid] {
			continue
		}
		for _, ov := range set.future {
			if e, ok := materialize(ov, ov.start, true); ok && overlaps(e, windowStart, windowEnd) {
				events = append(events, e)
			}
		}
	}

	sort.Slice(events, func(i, j int) bool {
		if events[i].Start.Equal(events[j].Start) {
			return events[i].Summary < events[j].Summary
		}
		return events[i].Start.Before(events[j].Start)
	})

	// A zone that could not be placed produced times from the local fallback,
	// which look ordinary and are wrong by whatever the offsets differ by. Said
	// once per calendar rather than per event.
	if unresolved := tz.Unresolved(); len(unresolved) > 0 {
		log.WithField("tzids", unresolved).Warn(
			"calendar names timezones that are neither IANA nor defined in the feed; " +
				"their events fall back to the server's local time")
	}

	return events, nil
}

// buildTemplate reads one VEVENT into a timezone-resolved template.
func buildTemplate(event *ics.VEvent, tz *tzResolver) (*eventTemplate, error) {
	tpl := &eventTemplate{
		base:    Event{UID: event.Id()},
		exdates: make(map[time.Time]bool),
	}

	if prop := event.GetProperty(ics.ComponentPropertySummary); prop != nil {
		tpl.base.Summary = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyLocation); prop != nil {
		tpl.base.Location = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyStatus); prop != nil {
		tpl.base.Status = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyDescription); prop != nil {
		tpl.base.Description = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyOrganizer); prop != nil {
		tpl.base.Organizer = prop.Value
	}
	if prop := event.GetProperty(ics.ComponentPropertyRrule); prop != nil {
		tpl.rrule = prop.Value
		tpl.base.RecurRule = prop.Value
	}

	for _, prop := range event.Properties {
		switch prop.IANAToken {
		case string(ics.ComponentPropertyAttendee):
			tpl.base.Attendees = append(tpl.base.Attendees, prop.Value)
		case string(ics.ComponentPropertyCategories):
			// CATEGORIES is a comma-separated list within a single property.
			for _, c := range strings.Split(prop.Value, ",") {
				if c = strings.TrimSpace(c); c != "" {
					tpl.base.Categories = append(tpl.base.Categories, c)
				}
			}
		}
	}

	// DTSTART is mandatory; without it the event cannot be placed in time.
	dtstart := event.GetProperty(ics.ComponentPropertyDtStart)
	if dtstart == nil {
		return nil, fmt.Errorf("event %q has no DTSTART", tpl.base.UID)
	}
	start, allDay, err := parseDateTime(dtstart.Value, paramTZID(dtstart), tz)
	if err != nil {
		return nil, err
	}
	tpl.start = start
	tpl.base.AllDay = allDay

	// Only a zoned date-time repeats on a wall clock. A UTC value genuinely
	// repeats on the timeline, and a floating one is already resolved against
	// time.Local, which tracks its own transitions.
	if tpl.tzid = paramTZID(dtstart); tpl.tzid != "" {
		if wall, ok := wallClock(dtstart.Value); ok {
			tpl.startWall, tpl.wallBased = wall, true
		}
	}

	// Duration comes from DTEND, or DURATION, or defaults by event kind.
	tpl.duration = eventDuration(event, start, allDay, tz)

	if p := event.GetProperty(ics.ComponentProperty(ics.PropertyRecurrenceId)); p != nil {
		if rid, _, err := parseDateTime(p.Value, paramTZID(p), tz); err == nil {
			tpl.recurrenceID = rid
			tpl.hasRecurID = true
			tpl.thisAndFuture = strings.EqualFold(paramValue(p, "RANGE"), "THISANDFUTURE")
		}
	}

	// EXDATE and RDATE may each appear multiple times, and each may carry a
	// comma-separated list of values.
	for _, prop := range event.Properties {
		switch prop.IANAToken {
		case string(ics.PropertyExdate):
			for _, v := range strings.Split(prop.Value, ",") {
				if t, _, err := parseDateTime(strings.TrimSpace(v), paramTZID(&prop), tz); err == nil {
					tpl.exdates[t.UTC()] = true
				}
			}
		case string(ics.PropertyRdate):
			for _, v := range strings.Split(prop.Value, ",") {
				// RDATE values may be periods ("start/end"); take the start.
				v = strings.TrimSpace(v)
				if i := strings.Index(v, "/"); i > 0 {
					v = v[:i]
				}
				if t, _, err := parseDateTime(v, paramTZID(&prop), tz); err == nil {
					tpl.rdates = append(tpl.rdates, t)
				}
			}
		}
	}

	return tpl, nil
}

// wallClock reads the local date-time form, the only one that carries a wall
// clock needing a zone to place it. Date-only and UTC values are rejected.
func wallClock(value string) (time.Time, bool) {
	value = strings.TrimSpace(value)
	if len(value) == 8 || strings.HasSuffix(value, "Z") {
		return time.Time{}, false
	}
	t, err := time.ParseInLocation("20060102T150405", value, time.UTC)
	if err != nil {
		return time.Time{}, false
	}
	return t, true
}

func paramTZID(prop *ics.IANAProperty) string {
	return paramValue(prop, string(ics.PropertyTzid))
}

func paramValue(prop *ics.IANAProperty, name string) string {
	if prop == nil {
		return ""
	}
	if vals, ok := prop.ICalParameters[name]; ok && len(vals) > 0 {
		return vals[0]
	}
	return ""
}

// parseDateTime interprets an iCalendar date or date-time value. It reports
// whether the value was a date-only (all-day) form.
func parseDateTime(value, tzid string, tz *tzResolver) (time.Time, bool, error) {
	value = strings.TrimSpace(value)

	// Date-only form: YYYYMMDD (all-day).
	if len(value) == 8 {
		t, err := time.ParseInLocation("20060102", value, time.UTC)
		if err != nil {
			return time.Time{}, false, err
		}
		if loc := tz.load(tzid, t); loc != nil {
			t, _ = time.ParseInLocation("20060102", value, loc)
		}
		return t, true, nil
	}

	// UTC form: YYYYMMDDTHHMMSSZ.
	if strings.HasSuffix(value, "Z") {
		t, err := time.ParseInLocation("20060102T150405Z", value, time.UTC)
		if err != nil {
			return time.Time{}, false, err
		}
		return t, false, nil
	}

	// Local form: YYYYMMDDTHHMMSS, interpreted in TZID if present.
	naive, err := time.ParseInLocation("20060102T150405", value, time.UTC)
	if err != nil {
		return time.Time{}, false, err
	}
	loc := tz.load(tzid, naive)
	if loc == nil {
		// Floating time, or an unresolvable zone: fall back to local time so the
		// event still lands on the correct calendar day.
		loc = time.Local
	}
	t, err := time.ParseInLocation("20060102T150405", value, loc)
	if err != nil {
		return time.Time{}, false, err
	}
	return t, false, nil
}

// eventDuration derives the length of an event from DTEND or DURATION.
func eventDuration(event *ics.VEvent, start time.Time, allDay bool, tz *tzResolver) time.Duration {
	if dtend := event.GetProperty(ics.ComponentProperty(ics.PropertyDtend)); dtend != nil {
		if end, _, err := parseDateTime(dtend.Value, paramTZID(dtend), tz); err == nil {
			if d := end.Sub(start); d >= 0 {
				return d
			}
		}
	}
	if dur := event.GetProperty(ics.ComponentProperty(ics.PropertyDuration)); dur != nil {
		if d, err := parseICalDuration(dur.Value); err == nil && d >= 0 {
			return d
		}
	}
	if allDay {
		return 24 * time.Hour
	}
	// RFC 5545: a date-time DTSTART with no DTEND or DURATION is instantaneous.
	return 0
}

// parseICalDuration parses an RFC 5545 duration such as "PT1H30M" or "P2DT3H".
func parseICalDuration(s string) (time.Duration, error) {
	s = strings.TrimSpace(s)
	neg := false
	if strings.HasPrefix(s, "-") {
		neg = true
		s = s[1:]
	} else if strings.HasPrefix(s, "+") {
		s = s[1:]
	}
	if !strings.HasPrefix(s, "P") {
		return 0, fmt.Errorf("invalid duration %q", s)
	}
	s = s[1:]

	var total time.Duration
	var num int
	inTime := false
	seenDigit := false

	for _, r := range s {
		switch {
		case r >= '0' && r <= '9':
			num = num*10 + int(r-'0')
			seenDigit = true
		case r == 'T':
			inTime = true
			num, seenDigit = 0, false
		case r == 'W' && seenDigit:
			total += time.Duration(num) * 7 * 24 * time.Hour
			num, seenDigit = 0, false
		case r == 'D' && seenDigit:
			total += time.Duration(num) * 24 * time.Hour
			num, seenDigit = 0, false
		case r == 'H' && inTime && seenDigit:
			total += time.Duration(num) * time.Hour
			num, seenDigit = 0, false
		case r == 'M' && inTime && seenDigit:
			total += time.Duration(num) * time.Minute
			num, seenDigit = 0, false
		case r == 'S' && inTime && seenDigit:
			total += time.Duration(num) * time.Second
			num, seenDigit = 0, false
		default:
			return 0, fmt.Errorf("invalid duration %q", s)
		}
	}
	if neg {
		total = -total
	}
	return total, nil
}

// pad is how far outside a window a wall-clock expansion has to reach: enough
// for any zone offset, generously rounded up, plus the event's own length so an
// occurrence starting before the window but running into it is still produced.
func pad(duration time.Duration) time.Duration { return duration + 36*time.Hour }

// expand returns the start instants of a template within the window, honouring
// RRULE, RDATE and EXDATE.
func expand(tpl *eventTemplate, tz *tzResolver, windowStart, windowEnd time.Time) []time.Time {
	var out []time.Time
	if tpl.rrule != "" {
		out = tpl.expandRule(tz, windowStart, windowEnd)
	} else {
		// RFC 5545 §3.8.5.2: the recurrence set is DTSTART together with RRULE
		// and RDATE, minus EXDATE. DTSTART belongs to it even when RDATE is the
		// only recurrence property, and an event carrying RDATE alone otherwise
		// loses the occurrence it was written for.
		out = append(out, tpl.start)
	}
	out = append(out, tpl.rdates...)

	filtered := out[:0]
	seen := make(map[time.Time]bool, len(out))
	for _, t := range out {
		key := t.UTC()
		if tpl.exdates[key] || seen[key] {
			continue
		}
		seen[key] = true
		filtered = append(filtered, t)
	}
	return filtered
}

// expandRule materializes the occurrences of an RRULE inside the window.
//
// A series written in a named zone repeats on the wall clock, not on the
// timeline: a 10:00 standup is at 10:00 either side of a DST transition. So it
// is expanded in wall-clock space and each occurrence placed afterwards, asking
// the zone which offset applied on that occurrence's own date.
//
// Expanding from the resolved instant instead pins every occurrence to the
// offset in force when the series began. That is invisible for a zone that
// resolves to an IANA location, because rrule then repeats on that location's
// wall clock anyway — and wrong for one resolved from the feed's own VTIMEZONE,
// which can only be represented as a fixed offset.
func (tpl *eventTemplate) expandRule(tz *tzResolver, windowStart, windowEnd time.Time) []time.Time {
	opt, err := rrule.StrToROption(tpl.rrule)
	if err != nil {
		// An unparseable rule still has a real first occurrence.
		return []time.Time{tpl.start}
	}

	opt.Dtstart = tpl.start
	if tpl.wallBased {
		opt.Dtstart = tpl.startWall
	}

	// UNTIL is defined in UTC even when DTSTART is a local time, so during a
	// wall-clock expansion rrule would be comparing two different clocks and
	// end the series off by the zone's offset — keeping a trailing occurrence
	// west of UTC, dropping a real final one east of it. The bound is lifted
	// out of rrule's hands and applied below to the placed instant, which is
	// the thing UNTIL actually describes.
	until := opt.Until
	if tpl.wallBased && !until.IsZero() {
		opt.Until = until.Add(pad(tpl.duration))
	}

	rr, err := rrule.NewRRule(*opt)
	if err != nil {
		return []time.Time{tpl.start}
	}

	queryStart, queryEnd := windowStart.Add(-tpl.duration), windowEnd
	if tpl.wallBased {
		queryStart, queryEnd = windowStart.Add(-pad(tpl.duration)), windowEnd.Add(pad(tpl.duration))
	}

	var out []time.Time
	for _, t := range rr.Between(queryStart, queryEnd, true) {
		at := t
		if tpl.wallBased {
			at = tz.resolveWall(t, tpl.tzid)
		}
		if !until.IsZero() && at.After(until) {
			continue
		}
		out = append(out, at)
		if len(out) >= maxOccurrencesPerSeries {
			break
		}
	}
	return out
}

// materialize produces a concrete Event for one occurrence instant.
func materialize(tpl *eventTemplate, start time.Time, recurring bool) (Event, bool) {
	if start.IsZero() {
		return Event{}, false
	}
	e := tpl.base
	e.Start = start
	e.End = start.Add(tpl.duration)
	e.Recurring = recurring
	// Copy slices so expanded occurrences do not alias one another.
	if len(tpl.base.Attendees) > 0 {
		e.Attendees = append([]string(nil), tpl.base.Attendees...)
	}
	if len(tpl.base.Categories) > 0 {
		e.Categories = append([]string(nil), tpl.base.Categories...)
	}
	return e, true
}

// overlaps reports whether an event intersects the window. An event that starts
// before the window but is still running inside it counts as overlapping;
// zero-length events count when they fall on the window's start boundary.
func overlaps(e Event, windowStart, windowEnd time.Time) bool {
	if !e.Start.Before(windowEnd) {
		return false
	}
	if e.End.Equal(e.Start) {
		return !e.Start.Before(windowStart)
	}
	return e.End.After(windowStart)
}
